/*职位状态*/
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'WORK_STAT', null, 0, '离职', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'WORK_STAT', null, 1, '在职', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'WORK_STAT', null, 2, '请假', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'WORK_STAT', null, 3, '出差', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
commit;

/*职位*/
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10001, '董事长', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10002, '行政主管', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10003, '行政专员', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10004, '人事主管', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10005, '人事专员', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10006, '部门经理', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10007, '开发主管', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10008, '测试主管', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 10009, '运维主管', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 100010, '运维工程师', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 100011, '测试工程师', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
insert into OA_DICT (ID, ITEM_NAME, P_KEY, KEY, VALUE, COMMENTS, CREATED_DATE, CREATED_BY, UPDATE_DATE, UPDATE_BY) values (SYS_GUID(), 'POSITION', null, 100012, 'java开发工程师', null, SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM');
commit;