-- CREATE TABLE
CREATE TABLE PERSON
(
    IDCARD_NO             VARCHAR2(18) NOT NULL,
    NAME                  VARCHAR2(40) NOT NULL,
    GENDER                VARCHAR2(10),
    BIRTH_DATE            DATE,
    AGE                   NUMBER,
    NATIVE_PLACE_CODE     NUMBER,
    PROFESSION_CODE       NUMBER,
    GRANDUATE_SCHOOL_CODE NUMBER,
    CREATED_DATE          DATE,
    CREATED_BY            VARCHAR2(40),
    UPATE_DATE            DATE,
    UPDATE_BY             VARCHAR2(40),
    HOME_PROVINCE         NUMBER(6),
    HOME_CITY             NUMBER(6),
    HOME_AREA             NUMBER(6),
    WORK_PROVINCE         NUMBER(6),
    WORK_CITY             NUMBER(6),
    WORK_AREA             NUMBER(6)
)
    TABLESPACE USERS
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN PERSON.IDCARD_NO
  IS '身份证号';
COMMENT ON COLUMN PERSON.NAME
  IS '姓名';
COMMENT ON COLUMN PERSON.GENDER
  IS '性别 M:男性 F:女性 空：未知';
COMMENT ON COLUMN PERSON.BIRTH_DATE
  IS '出生日期';
COMMENT ON COLUMN PERSON.AGE
  IS '年龄';
COMMENT ON COLUMN PERSON.NATIVE_PLACE_CODE
  IS '籍贯';
COMMENT ON COLUMN PERSON.PROFESSION_CODE
  IS '职业编码';
COMMENT ON COLUMN PERSON.GRANDUATE_SCHOOL_CODE
  IS '毕业学校编码';
COMMENT ON COLUMN PERSON.CREATED_DATE
  IS '创建时间';
COMMENT ON COLUMN PERSON.CREATED_BY
  IS '创建人';
COMMENT ON COLUMN PERSON.UPATE_DATE
  IS '更新时间';
COMMENT ON COLUMN PERSON.UPDATE_BY
  IS '更新人';
COMMENT ON COLUMN PERSON.HOME_PROVINCE
  IS '家庭地址（省）';
COMMENT ON COLUMN PERSON.HOME_CITY
  IS '家庭地址（市）';
COMMENT ON COLUMN PERSON.HOME_AREA
  IS '家庭地址（区）';
COMMENT ON COLUMN PERSON.WORK_PROVINCE
  IS '工作地址（省）';
COMMENT ON COLUMN PERSON.WORK_CITY
  IS '工作地址（市）';
COMMENT ON COLUMN PERSON.WORK_AREA
  IS '工作地址（区）';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE PERSON
    ADD PRIMARY KEY (IDCARD_NO)
    USING INDEX
  TABLESPACE USERS
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

-- Add/modify columns
alter table PERSON add favorite NUMBER(1);
-- Add comments to the columns
comment on column PERSON.favorite
  is '收藏（1:收藏，0：取消收藏）';