DROP TABLE SYS_AREA;
CREATE TABLE SYS_AREA(
    AREA_ID NUMBER(6) NOT NULL PRIMARY KEY,
    AREA_NAME VARCHAR2(40) NOT NULL,
    CITY_ID  NUMBER(6)
);
COMMENT ON COLUMN SYS_AREA.AREA_ID IS '区id';
COMMENT ON COLUMN SYS_AREA.AREA_NAME IS '区';
COMMENT ON COLUMN SYS_AREA.CITY_ID IS '所属城市id';