DROP TABLE SYS_PROVINCE;
CREATE TABLE SYS_PROVINCE(
    PROVINCE_ID NUMBER(6) NOT NULL PRIMARY KEY,
    PROVINCE_NAME VARCHAR2(40) NOT NULL
);
COMMENT ON COLUMN SYS_PROVINCE.PROVINCE_ID IS '省份id';
COMMENT ON COLUMN SYS_PROVINCE.PROVINCE_NAME IS '省份';
