--市
DROP TABLE SYS_CITY;
CREATE TABLE SYS_CITY(
    CITY_ID NUMBER(6) NOT NULL PRIMARY KEY,
    CITY_NAME VARCHAR2(40) NOT NULL,
    PROVINCE_ID  NUMBER(6)
);
COMMENT ON COLUMN SYS_CITY.CITY_ID IS '城市id';
COMMENT ON COLUMN SYS_CITY.CITY_NAME IS '城市';
COMMENT ON COLUMN SYS_CITY.PROVINCE_ID IS '所属省份id';