DROP TABLE CV_DEPT;
CREATE TABLE CV_DEPT(
                        ID NUMBER(4) NOT NULL PRIMARY KEY,
                        NAME VARCHAR2(64),
                        PARENT_ID NUMBER(4),
                        DPT_PATH VARCHAR2(64),
                        ENABLED NUMBER(1),
                        IS_PARENT NUMBER(1)
);
COMMENT ON TABLE CV_DEPT IS 'Convey部门表';
COMMENT ON COLUMN CV_DEPT.ID IS 'id主键';
COMMENT ON COLUMN CV_DEPT.NAME IS '部门名称';
COMMENT ON COLUMN CV_DEPT.PARENT_ID IS '父节点';
COMMENT ON COLUMN CV_DEPT.DPT_PATH IS '部门路径';
COMMENT ON COLUMN CV_DEPT.ENABLED IS '是否启用';
COMMENT ON COLUMN CV_DEPT.IS_PARENT IS '是否父节点';