DROP TABLE CV_MENU;
CREATE TABLE CV_MENU(
       ID NUMBER(11) NOT NULL PRIMARY KEY,
       PATTERN VARCHAR2(11)
);
COMMENT ON TABLE CV_USER_ROLE IS 'Convey系统资源表';
COMMENT ON COLUMN CV_USER_ROLE.ID IS 'id主键';
COMMENT ON COLUMN CV_USER_ROLE.USER_ID IS '菜单';