DROP TABLE CV_ROLE_MENU;
CREATE TABLE CV_ROLE_MENU(
       ID NUMBER(11) NOT NULL PRIMARY KEY,
       MENU_ID NUMBER(11),
       ROLE_ID NUMBER(11)
);
COMMENT ON TABLE CV_ROLE_MENU IS 'Convey系统资源表';
COMMENT ON COLUMN CV_USER_ROLE.ID IS 'id主键';
COMMENT ON COLUMN CV_ROLE_MENU.MENU_ID IS '菜单id';
COMMENT ON COLUMN CV_ROLE_MENU.ROLE_ID IS '角色id';