DROP TABLE CV_ROLE;
CREATE TABLE CV_ROLE(
         ID NUMBER(11) NOT NULL PRIMARY KEY,
         ROLE VARCHAR2(64),
         ROLE_NAME VARCHAR2(64),
         CREATED_DATE DATE,
         CREATED_BY   VARCHAR2(40),
         UPATE_DATE DATE,
         UPDATE_BY VARCHAR2(40)
  );
COMMENT ON TABLE CV_USER IS 'Convey系统角色表';
COMMENT ON COLUMN CV_USER.ID IS 'id主键';
COMMENT ON COLUMN CV_USER.WORK_ID IS '角色';
COMMENT ON COLUMN CV_USER.ACCT IS '角色中文名称';
COMMENT ON COLUMN CV_USER.CREATED_DATE IS '创建时间';
COMMENT ON COLUMN CV_USER.CREATED_BY IS '创建人';
COMMENT ON COLUMN CV_USER.UPATE_DATE IS '更新时间';
COMMENT ON COLUMN CV_USER.UPDATE_BY IS '更新人';